### ISSUE TITLE
[Feature Request]: Fully client-side mod

### ISSUE THREAD

**Issue by DanexaPlay** [LukenSkyne/Minecraft-Ping-Wheel#23] opened 2023-10-29 10:23 UTC
Hi, i really like your ping wheel mod. My minecraft squad usually fights with others and we actually need this mod but just for client side, because we play on on other servers that don't have this mod.
I know that would be really hard to add, but this would be very useful for us. Thank you

**Comment by LukenSkyne** [comment] 2023-10-29 11:54
Hey, glad you like the mod!

We understand that in some situations, players would love to use the mod without it being installed on the server directly. The approach we've been considering was to provide a separate, third-party server application, that would allow your clients to communicate independently of the game server you are playing on.

This approach, however, prevents server owners from deciding if they want to allow or deny the use of Ping Wheel in their community, which is why we are currently not planning to implement such a feature.

I hope you understand our view on this problem!

**Comment by LukenSkyne** [comment] 2023-10-29 11:55
Duplicate of #14

**Closed as not planned** 2023-10-29 11:55 UTC
Labels: enhancement :sparkles:
