### ISSUE TITLE
[Feature Request]: Locking settings for multiplayer servers?

### ISSUE THREAD

**Issue by KateReller** [LukenSkyne/Minecraft-Ping-Wheel#32] opened 2024-02-24 03:18 UTC
I do not know if this feature is in here, but I want to lock the settings for players that join the server. Things like limiting the distance of a ping, and removing the 'global' channel for pings.

**Comment by LukenSkyne** [comment] 2024-02-24 15:31
Hey, we previously discussed server-side configuration in #12. Feel free to provide a use-case where disabling the global channel seems necessary to you.

**Comment by LukenSkyne** [comment] 2024-02-24 15:31
Duplicate of #12

**Comment by LukenSkyne** [comment] 2024-03-03 16:14
Since I was working on rate limiting for version 1.8, I also included an option to disable the global channel in the [server config](https://github.com/LukenSkyne/Minecraft-Ping-Wheel/wiki/Server-and-Client-configuration#server).
Limiting the distance on the server is currently not planned.

**Closed as completed by LukenSkyne** 2024-03-03 16:14 UTC
Labels: enhancement :sparkles:
