### ISSUE TITLE
[Bug]: Misaligned on-screen ping markers

### ISSUE THREAD

**Issue by jfsawin** [LukenSkyne/Minecraft-Ping-Wheel#27] opened 2023-11-13 02:01 UTC
### Preflight Checklist

- [X] I am using the [latest version](https://github.com/LukenSkyne/Minecraft-Ping-Wheel/releases) of Ping Wheel for the corresponding mod loader.
- [X] The server I am playing on has Ping Wheel installed.
- [X] I have searched the [issue tracker](https://github.com/LukenSkyne/Minecraft-Ping-Wheel/issues?q=is%3Aissue) for a bug report that matches the one I want to file, without success.

### Which mod loaders have you experienced the issue with?

Fabric

### What versions of Minecraft have you experienced the issue in?

1.20–1.20.1

### Expected Behavior

Ping locations should be placed on the screen where the cursor is.

### Actual Behavior

The ping displays on my screen off to the side, sort of "orbiting" around the correct position.

### Logs URL

https://mclo.gs/M6aDMPV

### Additional Information

The actual marker in the game world seems to be correctly located, because the distance to the spot I mark is accurate, but the on-screen display of where the location is doesn't work correctly at all for me.

<img width="2527" alt="image" src="https://github.com/LukenSkyne/Minecraft-Ping-Wheel/assets/6720254/807d6818-7ec1-4552-839c-a93a071c0bd3">

In this screenshot, I have pinged the wall directly in front of me where the crosshair is, but the on-screen display is not positioned there. This happens no matter how near or far the location is, and it happens every time.

More information about my environment: I'm running Minecraft 1.20.1 on MacOS 14.1.1 with Java 17. My server is using Fabric 0.14.24. You can find my current modlist in the uploaded log.

**Comment by LukenSkyne** [comment] 2023-11-13 10:27
Thanks for reporting!

I would like to find out if this is an incompatibility with any of the installed mods in your instance.
From previous testing, I know that most performance mods should work just fine with Ping Wheel.

Can you try to reproduce the bug in a fresh instance of 1.20.1 with just Ping Wheel (+ Fabric API)?
If you are playing a public modpack, please provide a link to it.

**Comment by RXJpaw** [comment] 2023-11-13 11:56
Could not reproduce with the latest versions of the mods listed in the provided log. (Windows 10.0.19045.3636)

**Comment by RXJpaw** [comment] 2023-11-13 13:02
We've found that the current method of projecting world coordinates to the player's screen is flawed in MacOS. Luckily we already are in the process of rewriting this method anyways. 1.7.0 will fix this problem.

**Comment by LukenSkyne** [comment] 2023-11-16 16:18
Fixed in v1.7.0

**Closed as completed by LukenSkyne** 2023-11-16 16:18 UTC
Labels: bug :bug:
